/*
 * Copyright 2010 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 * 
 */



import droolsexample.*

rule "Score Náuseas/Mareos/Vómitos/"
 salience 200
when
    pac: Paciente($id:id);
    sin: Sintoma (idPaciente == $id, tipo == TipoSintoma.NÁUSEAS || tipo == TipoSintoma.VÓMITOS || tipo == TipoSintoma.MAREOS
                                    || tipo == TipoSintoma.SUDORACIÓN);
   $diagnostico: Diagnostico($score:score, idPac == $id);
then
    $diagnostico.setScore($score+25); 
end

rule "Score Edad Y Sexo Maculino"
 salience 200
when
    pac: Paciente($id:id, sexo == Sexo.MASCULINO, edad >= 50);
   $diagnostico: Diagnostico(idPac == $id, $score:score);
then
   $diagnostico.setScore($score+75);
end

rule "Score Edad Y Sexo Femenino"
 salience 200
when
    pac: Paciente($id:id, sexo == Sexo.FEMENINO, edad >= 60);
   $diagnostico: Diagnostico(idPac == $id, $score:score);
then
   $diagnostico.setScore($score+75);
end

rule "Score Factores De Riesgo"
 salience 200
when
    pac: Paciente($id:id);
    fRiesgo: FactoresRiesgo (idPacient == $id, factorRiesgo== EnumFRiesgo.HIPERTENSION || factorRiesgo== EnumFRiesgo.TABAQUISMO || 
                              factorRiesgo== EnumFRiesgo.DIABETES || factorRiesgo== EnumFRiesgo.COLESTEROL_ELEVADO ||
                              factorRiesgo== EnumFRiesgo.OBESIDAD || factorRiesgo== EnumFRiesgo.HISTORIAL_FAMILIAR)
   $diagnostico: Diagnostico(idPac == $id, $score:score);
then
   $diagnostico.setScore($score+50);
end

rule "Evaluar Cardiopatía Isquémica Con Credibilidad Baja"
  salience 150
when
    pac: Paciente($id:id);
    exists(Sintoma (idPaciente == $id, tipo == TipoSintoma.DOLOR_TORÁCICO));
    exists(Sintoma (idPaciente == $id, tipo ==TipoSintoma.DIFICULTAD_RESPIRAR));
    exists (Sintoma (idPaciente == $id, tipo == TipoSintoma.DOLOR_PECHO || tipo == TipoSintoma.DOLOR_CUELLO || tipo == TipoSintoma.DOLOR_BRAZO_IZQUIERDO
                                    || tipo == TipoSintoma.DOLOR_MANDIBULA));
$diagnostico: Diagnostico(idPac == $id);
then
  modify($diagnostico) {
        setCardiopatia(Boolean.TRUE),
        setCredibilidad(EnumCredibilidad.BAJA)
    }
end


rule "Evaluar Cardiopatía Isquémica Con Credibilidad Alta"
  salience 100
when
    pac: Paciente($id:id);
    $diagnostico: Diagnostico(idPac == $id, cardiopatia==Boolean.TRUE, score>=200);
    // 2 factores de riesgo (2*50) + 75 de edad + 1 síntoma malestar (+25)
then
        $diagnostico.setCredibilidad(EnumCredibilidad.ALTA);
end

rule "Evaluar Cardiopatía Isquémica Con Credibilidad Media"
  salience 100
when
    pac: Paciente($id:id);
    $diagnostico: Diagnostico(idPac == $id, cardiopatia==Boolean.TRUE, score<200 && score!=0);
then
        $diagnostico.setCredibilidad(EnumCredibilidad.MEDIA);
end

rule "Evaluar No Cardiopatía Isquémica "
  salience 100
when
    pac: Paciente($id:id);
    $diagnostico: Diagnostico(idPac == $id, cardiopatia==Boolean.FALSE);
then
        $diagnostico.setCredibilidad(EnumCredibilidad.ALTA);

end