/*
 * Copyright 2010 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 * 
 */



import droolsexample.*

rule "Score Náuseas"
 salience 200
when
    pac: Paciente($id:id);
    sin: Sintoma (idPaciente == $id, tipo == TipoSintoma.NÁUSEAS);
   $diagnostico: Diagnostico($score:score, idPac == $id);
then
    $diagnostico.setScore($score+25); 
end

rule "Score Mareos"
 salience 200
when
    pac: Paciente($id:id);
    sin: Sintoma (idPaciente == $id,  tipo == TipoSintoma.MAREOS);
   $diagnostico: Diagnostico($score:score, idPac == $id);
then
    $diagnostico.setScore($score+25); 
end

rule "Score Vómitos"
 salience 200
when
    pac: Paciente($id:id);
    sin: Sintoma (idPaciente == $id,  tipo == TipoSintoma.VÓMITOS);
   $diagnostico: Diagnostico($score:score, idPac == $id);
then
    $diagnostico.setScore($score+25); 
end

rule "Score Sudoración fría"
 salience 200
when
    pac: Paciente($id:id);
    sin: Sintoma (idPaciente == $id,tipo == TipoSintoma.SUDORACIÓN);
   $diagnostico: Diagnostico($score:score, idPac == $id);
then
    $diagnostico.setScore($score+25); 
end

rule "Score Dolor Torácico"
  salience 200
when
    pac: Paciente($id:id);
    sin: Sintoma (idPaciente == $id, tipo == TipoSintoma.DOLOR_TORÁCICO);
    $diagnostico: Diagnostico($score:score, idPac == $id);
then
    $diagnostico.setScore($score+75); 
end

rule "Score Dificultad Respirar"
  salience 200
when
    pac: Paciente($id:id);
    sin: Sintoma (idPaciente == $id, tipo ==TipoSintoma.DIFICULTAD_RESPIRAR);
    $diagnostico: Diagnostico($score:score, idPac == $id);
then
    $diagnostico.setScore($score+75); 
end

rule "Score Dolor Pecho"
  salience 200
when
    pac: Paciente($id:id);
    sin: Sintoma (idPaciente == $id, tipo == TipoSintoma.DOLOR_PECHO);
 $diagnostico: Diagnostico($score:score, idPac == $id);
then
    $diagnostico.setScore($score+75); 
end

rule "Score Dolor Cuello"
  salience 200
when
    pac: Paciente($id:id);
    sin: Sintoma (idPaciente == $id, tipo == TipoSintoma.DOLOR_CUELLO);
 $diagnostico: Diagnostico($score:score, idPac == $id);
then
    $diagnostico.setScore($score+75); 
end

rule "Score Dolor Brazo Izquierdo"
  salience 200
when
    pac: Paciente($id:id);
    sin: Sintoma (idPaciente == $id, tipo == TipoSintoma.DOLOR_BRAZO_IZQUIERDO);
 $diagnostico: Diagnostico($score:score, idPac == $id);
then
    $diagnostico.setScore($score+75); 
end

rule "Score Dolor Mandíbula"
  salience 200
when
    pac: Paciente($id:id);
    sin: Sintoma (idPaciente == $id,tipo == TipoSintoma.DOLOR_MANDIBULA);
 $diagnostico: Diagnostico($score:score, idPac == $id);
then
    $diagnostico.setScore($score+75); 
end

rule "Score Nitroglicerina"
  salience 200
when
    pac: Paciente($id:id);
    sin: Sintoma (idPaciente == $id, tipo == TipoSintoma.EFECTO_A_NITOGLICERINA_SUBLINGUAL);
 $diagnostico: Diagnostico($score:score, idPac == $id);
then
    $diagnostico.setScore($score+75); 
end

rule "Score Edad Y Sexo Maculino"
 salience 200
when
    pac: Paciente($id:id, sexo == Sexo.MASCULINO, edad >= 50);
   $diagnostico: Diagnostico(idPac == $id, $score:score);
then
   $diagnostico.setScore($score+75);
end

rule "Score Edad Y Sexo Femenino"
 salience 200
when
    pac: Paciente($id:id, sexo == Sexo.FEMENINO, edad >= 60);
   $diagnostico: Diagnostico(idPac == $id, $score:score);
then
   $diagnostico.setScore($score+75);
end

rule "Score Factores De Riesgo: Hipertensión"
 salience 200
when
    pac: Paciente($id:id);
    fRiesgo: FactoresRiesgo (idPacient == $id, factorRiesgo== EnumFRiesgo.HIPERTENSION);
   $diagnostico: Diagnostico(idPac == $id, $score:score);
then
   $diagnostico.setScore($score+50);
end

rule "Score Factores De Riesgo: Tabaquismo"
 salience 200
when
    pac: Paciente($id:id);
    fRiesgo: FactoresRiesgo (idPacient == $id, factorRiesgo== EnumFRiesgo.TABAQUISMO);
   $diagnostico: Diagnostico(idPac == $id, $score:score);
then
   $diagnostico.setScore($score+50);
end

rule "Score Factores De Riesgo: Diabetes"
 salience 200
when
    pac: Paciente($id:id);
    fRiesgo: FactoresRiesgo (idPacient == $id, factorRiesgo== EnumFRiesgo.DIABETES);
   $diagnostico: Diagnostico(idPac == $id, $score:score);
then
   $diagnostico.setScore($score+50);
end

rule "Score Factores De Riesgo: Colesterol"
 salience 200
when
    pac: Paciente($id:id);
    fRiesgo: FactoresRiesgo (idPacient == $id,factorRiesgo== EnumFRiesgo.COLESTEROL_ELEVADO);
   $diagnostico: Diagnostico(idPac == $id, $score:score);
then
   $diagnostico.setScore($score+50);
end

rule "Score Factores De Riesgo: Obesidad"
 salience 200
when
    pac: Paciente($id:id);
    fRiesgo: FactoresRiesgo (idPacient == $id, factorRiesgo== EnumFRiesgo.OBESIDAD);
   $diagnostico: Diagnostico(idPac == $id, $score:score);
then
   $diagnostico.setScore($score+50);
end

rule "Score Factores De Riesgo: Historial Familiar"
 salience 200
when
    pac: Paciente($id:id);
    fRiesgo: FactoresRiesgo (idPacient == $id, factorRiesgo== EnumFRiesgo.HISTORIAL_FAMILIAR);
   $diagnostico: Diagnostico(idPac == $id, $score:score);
then
   $diagnostico.setScore($score+50);
end

rule "Score Pruebas Complementarias: Necrosis"
  salience 200
when
    pac: Paciente($id:id);
    prueba: Pruebas (idPaciente == $id, tipo == EnumPruebas.NECROSIS);
 $diagnostico: Diagnostico(idPac == $id, $score:score);
then
   $diagnostico.setScore($score+150);
end

rule "Score Pruebas Complementarias: Oclusión Completa"
  salience 200
when
    pac: Paciente($id:id);
    prueba: Pruebas (idPaciente == $id, tipo == EnumPruebas.OCLUSIÓN_COMPLETA);
 $diagnostico: Diagnostico(idPac == $id, $score:score);
then
   $diagnostico.setScore($score+150);
end

rule "Score Pruebas Complementarias: Oclusión Parcial"
  salience 200
when
    pac: Paciente($id:id);
    prueba: Pruebas (idPaciente == $id, tipo == EnumPruebas.OCLUSIÓN_PARCIAL);
 $diagnostico: Diagnostico(idPac == $id, $score:score);
then
   $diagnostico.setScore($score+150);
end

rule "Score Pruebas Complementarias: Congestión Pulmonar"
  salience 200
when
    pac: Paciente($id:id);
    prueba: Pruebas (idPaciente == $id, tipo == EnumPruebas.CONGESTIÓN_PULMONAR);
 $diagnostico: Diagnostico(idPac == $id, $score:score);
then
   $diagnostico.setScore($score+150);
end

rule "Score Pruebas Complementarias: Cardiomegalia"
  salience 200
when
    pac: Paciente($id:id);
    prueba: Pruebas (idPaciente == $id, tipo == EnumPruebas.CARDIOMEGALIA);
 $diagnostico: Diagnostico(idPac == $id, $score:score);
then
   $diagnostico.setScore($score+150);
end

rule "Score Pruebas Complementarias: Infradesnivel ST"
  salience 200
when
    pac: Paciente($id:id);
    prueba: Pruebas (idPaciente == $id, tipo == EnumPruebas.INFRADESNIVEL_ST);
 $diagnostico: Diagnostico(idPac == $id, $score:score);
then
   $diagnostico.setScore($score+150);
end

rule "Score Pruebas Complementarias: Supradesnivel ST"
  salience 200
when
    pac: Paciente($id:id);
    prueba: Pruebas (idPaciente == $id, tipo == EnumPruebas.SUPRADESNIVEL_ST);
 $diagnostico: Diagnostico(idPac == $id, $score:score);
then
   $diagnostico.setScore($score+150);
end

rule "Score Pruebas Complementarias: Inversión T"
  salience 200
when
    pac: Paciente($id:id);
    prueba: Pruebas (idPaciente == $id, tipo == EnumPruebas.INVERSIÓN_T);
 $diagnostico: Diagnostico(idPac == $id, $score:score);
then
   $diagnostico.setScore($score+150);
end

rule "Score Pruebas Complementarias: Troponina"
  salience 200
when
    pac: Paciente($id:id);
    prueba: Pruebas (idPaciente == $id, tipo == EnumPruebas.ELEVADA_TROPONINA);
 $diagnostico: Diagnostico(idPac == $id, $score:score);
then
   $diagnostico.setScore($score+150);
end

rule "Score Pruebas Complementarias: Mioglobina"
  salience 200
when
    pac: Paciente($id:id);
    prueba: Pruebas (idPaciente == $id, tipo == EnumPruebas.ELEVADA_MIOGLOBINA);
 $diagnostico: Diagnostico(idPac == $id, $score:score);
then
   $diagnostico.setScore($score+150);
end

rule "Score Pruebas Complementarias: CK_MB"
  salience 200
when
    pac: Paciente($id:id);
    prueba: Pruebas (idPaciente == $id,tipo == EnumPruebas.ELEVADA_CK_MB);
 $diagnostico: Diagnostico(idPac == $id, $score:score);
then
   $diagnostico.setScore($score+150);
end

rule "Evaluar Cardiopatía Isquémica Con Credibilidad Baja"
  salience 150
when
    pac: Paciente($id:id);
    exists(Sintoma (idPaciente == $id, tipo == TipoSintoma.DOLOR_TORÁCICO));
    exists(Sintoma (idPaciente == $id, tipo ==TipoSintoma.DIFICULTAD_RESPIRAR));
    exists (Sintoma (idPaciente == $id, tipo == TipoSintoma.DOLOR_PECHO || tipo == TipoSintoma.DOLOR_CUELLO || tipo == TipoSintoma.DOLOR_BRAZO_IZQUIERDO
                                    || tipo == TipoSintoma.DOLOR_MANDIBULA));
$diagnostico: Diagnostico(idPac == $id);
then
  modify($diagnostico) {
        setCardiopatia(Boolean.TRUE),
        setCredibilidad(EnumCredibilidad.BAJA)
    }
end


rule "Evaluar Cardiopatía Isquémica Con Credibilidad Alta"
  salience 100
when
    pac: Paciente($id:id);
    $diagnostico: Diagnostico(idPac == $id, cardiopatia==Boolean.TRUE, score>=700);
then
        $diagnostico.setCredibilidad(EnumCredibilidad.ALTA);
end

rule "Evaluar Cardiopatía Isquémica Con Credibilidad Media"
  salience 100
when
    pac: Paciente($id:id);
    $diagnostico: Diagnostico(idPac == $id, cardiopatia==Boolean.TRUE, score>225 && score<700);
then
        $diagnostico.setCredibilidad(EnumCredibilidad.MEDIA);
end

rule "Evaluar No Cardiopatía Isquémica "
  salience 100
when
    pac: Paciente($id:id);
    $diagnostico: Diagnostico(idPac == $id, cardiopatia==Boolean.FALSE);
then
        $diagnostico.setCredibilidad(EnumCredibilidad.ALTA);
         $diagnostico.setComentario("Mantener una dieta equilibrada. Evitar el sedentarismo, el tabaquismo y el alcohol.");
end

rule "Evaluar Infarto Agudo de Miocardio"
  salience 50
when
    pac: Paciente($id:id);
    $diagnostico: Diagnostico(idPac == $id, cardiopatia==Boolean.TRUE);
    exists(Sintoma (idPaciente == $id, tipo == TipoSintoma.DURACIÓN_MAYOR_20));
    exists(Pruebas (idPaciente == $id, tipo == EnumPruebas.NECROSIS));
   exists(Pruebas (idPaciente == $id, tipo == EnumPruebas.OCLUSIÓN_COMPLETA || tipo == EnumPruebas.OCLUSIÓN_PARCIAL));
    exists(Pruebas (idPaciente == $id, tipo == EnumPruebas.CONGESTIÓN_PULMONAR || tipo == EnumPruebas.CARDIOMEGALIA));
   exists(Pruebas (idPaciente == $id, tipo == EnumPruebas.INFRADESNIVEL_ST || tipo == EnumPruebas.SUPRADESNIVEL_ST));
   exists(Pruebas (idPaciente == $id, tipo == EnumPruebas.INVERSIÓN_T));
    exists(Pruebas (idPaciente == $id, tipo == EnumPruebas.ELEVADA_TROPONINA));
  exists(Pruebas (idPaciente == $id, tipo == EnumPruebas.ELEVADA_MIOGLOBINA));
  exists(Pruebas (idPaciente == $id, tipo == EnumPruebas.ELEVADA_CK_MB));
  not (exists(Sintoma (idPaciente == $id, tipo == TipoSintoma.EFECTO_A_NITOGLICERINA_SUBLINGUAL)));
   not (exists(Sintoma (idPaciente == $id, tipo == TipoSintoma.APARICIÓN_ESFUERZO_FÍSICO)));
   not (exists(Sintoma (idPaciente == $id, tipo == TipoSintoma.DESAPARECE_EN_REPOSO)));
then
  modify($diagnostico) {
        setTipo(TipoCardiopatia.INFARTO_MIOCARDIO),
        setGravedad(Gravedad.ELEVADA),
         setComentario("Potencialmente mortal y grave. Requiere atención inmediata")
    }
end

rule "Evaluar Angina Pecho Estable Por Ejercicio Físico"
  salience 50
when
    pac: Paciente($id:id);
    $diagnostico: Diagnostico(idPac == $id, cardiopatia==Boolean.TRUE);
    exists(Sintoma (idPaciente == $id, tipo == TipoSintoma.DURACIÓN_MENOR_20));
   exists(Sintoma (idPaciente == $id, tipo == TipoSintoma.APARICIÓN_ESFUERZO_FÍSICO));
    exists(Sintoma (idPaciente == $id, tipo == TipoSintoma.DESAPARECE_EN_REPOSO));
   exists(Pruebas (idPaciente == $id,  tipo == EnumPruebas.OCLUSIÓN_PARCIAL));
   not  (exists(Pruebas (idPaciente == $id, tipo == EnumPruebas.NECROSIS)));
   not (exists(Pruebas (idPaciente == $id, tipo == EnumPruebas.ELEVADA_TROPONINA)));
  not (exists(Pruebas (idPaciente == $id, tipo == EnumPruebas.ELEVADA_MIOGLOBINA)));
   not (exists(Pruebas (idPaciente == $id, tipo == EnumPruebas.ELEVADA_CK_MB)));

then
  modify($diagnostico) {
        setTipo(TipoCardiopatia.ANGINA_ESTABLE),
        setGravedad(Gravedad.LEVE),
        setComentario("Menos grave, requiere atención médica.")
    }
end

rule "Evaluar Angina Pecho Estable Por Estrés Emocional"
  salience 50
when
    pac: Paciente($id:id);
    $diagnostico: Diagnostico(idPac == $id, cardiopatia==Boolean.TRUE);
    exists(Sintoma (idPaciente == $id, tipo == TipoSintoma.DURACIÓN_MENOR_20));
   exists(Sintoma (idPaciente == $id, tipo == TipoSintoma.APARICIÓN_ESTRÉS));
   exists(Pruebas (idPaciente == $id,  tipo == EnumPruebas.OCLUSIÓN_PARCIAL));
   not  (exists(Pruebas (idPaciente == $id, tipo == EnumPruebas.NECROSIS)));
   not (exists(Pruebas (idPaciente == $id, tipo == EnumPruebas.ELEVADA_TROPONINA)));
  not (exists(Pruebas (idPaciente == $id, tipo == EnumPruebas.ELEVADA_MIOGLOBINA)));
   not (exists(Pruebas (idPaciente == $id, tipo == EnumPruebas.ELEVADA_CK_MB)));

then
  modify($diagnostico) {
        setTipo(TipoCardiopatia.ANGINA_ESTABLE),
        setGravedad(Gravedad.LEVE),
        setComentario("Menos grave, requiere atención médica.")
    }
end

rule "Evaluar Angina Pecho Inestable"
  salience 50
when
    pac: Paciente($id:id);
    $diagnostico: Diagnostico(idPac == $id, cardiopatia==Boolean.TRUE);
    exists(Sintoma (idPaciente == $id, tipo == TipoSintoma.DURACIÓN_20));
   exists(Pruebas (idPaciente == $id,  tipo == EnumPruebas.OCLUSIÓN_PARCIAL));
   not (exists(Pruebas (idPaciente == $id, tipo == EnumPruebas.NECROSIS)));
   not (exists(Sintoma (idPaciente == $id, tipo == TipoSintoma.EFECTO_A_NITOGLICERINA_SUBLINGUAL)));
   not (exists(Sintoma (idPaciente == $id, tipo == TipoSintoma.APARICIÓN_ESFUERZO_FÍSICO)));
   not (exists(Sintoma (idPaciente == $id, tipo == TipoSintoma.DESAPARECE_EN_REPOSO)));

then
  modify($diagnostico) {
        setTipo(TipoCardiopatia.ANGINA_INESTABLE),
        setGravedad(Gravedad.MODERADA),
        setComentario("Si no se trata  puede llegar a infarto")
    }
end

rule "Evaluar Cardiopatía Isquémica No Concluyente"
  salience 25
when
    pac: Paciente($id:id);
    $diagnostico: Diagnostico(idPac == $id, cardiopatia==Boolean.TRUE, tipo==null);

then
  modify($diagnostico) {
        setGravedad(Gravedad.LEVE),
        setComentario("Los síntomas y las pruebas no son concluyentes para diagnosticar el tipo de cardiopatía isquémica")
    }
end