/*
 * Copyright 2010 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 * Author: Alberto Gil de la Fuente
 */



import droolsexample.ATM.Operation
import droolsexample.ATM.Tries

rule "authorization of operations"
    dialect "mvel"
    when
        op1 : Operation (verified == true, date_expired == false, pin == true, 
            tries == Tries.NOT_EXPIRED, balance >= price, limit >= price )
    then
// IF I WANT TO DEBUG THE CODE, I CAN PRINT HERE WHATEVER I WANT System.out.println( op );
        System.out.println( op1 + " authorized. ")
        modify (op1) { authorized = true}
end
